-- Update listings table with missing columns
ALTER TABLE listings ADD COLUMN IF NOT EXISTS brand TEXT;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS living_community TEXT;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS urgent BOOLEAN DEFAULT FALSE;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS event_date TIMESTAMP WITH TIME ZONE;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS venue TEXT;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS cover_image TEXT;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS sold_to_user_id TEXT REFERENCES users(uid);
